package m68k040.fuzz

import m68k040.VerilatorTest
import org.scalatest.funsuite.AnyFunSuite

/** End-to-end STORED-VALUE coverage for the `FMOVE FPn,<ea>` destinations that no oracle
  * can referee (Task 14b review, Important #5).
  *
  * Everything else about the store direction is already value-checked against Musashi in
  * `lockstep.FpuLockStepSpec` (`(An)`, `(An)+`, `-(An)`, `d16(An)`, `d8(An,Xn)`, abs.L, and
  * the full-width register-direct forms, each with a real `checkMem`/per-step comparison).
  * Two cases are structurally OUT of that spec's reach and were left with decode-shape
  * coverage only:
  *
  *   1. **abs.W destinations.** Musashi's FP write helpers have no mode-7/reg-0 arm at all
  *      and `fatalerror` out of the whole emulator ("M68kFPU: WRITE_EA_32: unhandled mode 7,
  *      reg 0"), so an abs.W destination kills the ORACLE, not the DUT. This core supports
  *      the form deliberately (design decision D6: Musashi's gap is emulator laziness, not
  *      an ISA restriction) -- which means the support has to be proven without it.
  *   2. **Register-direct `.W`/`.B` partial-register merge.** A confirmed oracle divergence
  *      (Divergence Register D11): Musashi's `WRITE_EA_16`/`WRITE_EA_8` assign
  *      `REG_D[reg] = data` from a uint16/uint8 and zero-extend over the whole register,
  *      where real 68k hardware merges into the low word/byte only. Proven at the EU level
  *      in `execute.FpuEuIntegrationSpec`; this is its end-to-end complement, through the
  *      real decoder, microcode and rename.
  *
  * The idiom is the corpus's own: a self-checking program whose PASS/FAIL is a sentinel
  * word, run on the shared full-core `FuzzCoreDut` via `PortedTestRunner` (no extra
  * Verilator compile). It lives here rather than in the vendored corpus directory because
  * that directory is regenerated by `tools/fuzz/vendor-ported-tests.sh` from the sibling
  * project and must not accumulate locally-authored tests. */
class FpStoreValueSpec extends AnyFunSuite {

  private val TimeoutCycles = 200000L

  private def runProgram(name: String, src: String): Unit =
    PortedTestRunner.run(name, src, TimeoutCycles) match {
      case PortedPass         => ()
      case PortedFail(word)   =>
        fail(f"[$name] FAIL sentinel word=0x$word%08x " +
             f"(expected 0x${PortedTestRunner.PassWord}%08x)")
      case PortedHang(cycles) => fail(s"[$name] HANG: no sentinel within $cycles cycles")
      case PortedGenFail(r)   => fail(s"[$name] assemble/toolchain error: $r")
    }

  /** FP0 = 1234.0 (int32 0x000004D2 -- low word 0x04D2, low byte 0xD2, three distinct
    * widths so a wrong-size store cannot alias) and FP1 = 4.0 (exactly representable in
    * single AND double: 0x40800000 / 0x4010000000000000, so the .S/.D images are
    * hand-verifiable rather than a rounding result). Every destination long is zeroed
    * FIRST, which is what turns "the word/byte landed" into "and nothing beside it moved". */
  private val absWProgram =
    """
    .text
    .org 0

    .equ PASS_SENT, 0xFFFF0000
    .equ W_L,  0x00003000
    .equ W_S,  0x00003010
    .equ W_D,  0x00003020
    .equ W_W,  0x00003030
    .equ W_B,  0x00003040

_start:
    lea     0x00010000, %a7
    move.l  #_fline, 0x0000002C

    | Define every checked span in the DUT's memory first (a partial store must be
    | provably partial, and unwritten backing memory is not zero-filled).
    lea     W_L, %a0
    moveq   #0, %d0
    move.l  %d0, (%a0)
    move.l  %d0, 16(%a0)
    move.l  %d0, 32(%a0)
    move.l  %d0, 36(%a0)
    move.l  %d0, 48(%a0)
    move.l  %d0, 64(%a0)

    fmove.l #1234, %fp0
    move.l  #0x40800000, %d0
    fmove.s %d0, %fp1

    | ---- the subject: five formats, all through an abs.W destination ----
    fmove.l %fp0, W_L:w
    fmove.w %fp0, W_W:w
    fmove.b %fp0, W_B:w
    fmove.s %fp1, W_S:w
    fmove.d %fp1, W_D:w

    move.l  W_L, %d1
    cmp.l   #0x000004D2, %d1
    bne     _fail_l

    | A WORD store at +0 leaves the low half of the long untouched (still zero).
    move.l  W_W, %d1
    cmp.l   #0x04D20000, %d1
    bne     _fail_w

    | Likewise a BYTE store: only the top byte of the long may have changed.
    move.l  W_B, %d1
    cmp.l   #0xD2000000, %d1
    bne     _fail_b

    move.l  W_S, %d1
    cmp.l   #0x40800000, %d1
    bne     _fail_s

    | Double is TWO chunks: high 32 bits at +0, low at +4.
    move.l  W_D, %d1
    cmp.l   #0x40100000, %d1
    bne     _fail_d
    move.l  W_D+4, %d1
    cmp.l   #0x00000000, %d1
    bne     _fail_d

    lea     PASS_SENT, %a1
    move.l  #0xC0FFEE00, %d2
    move.l  %d2, (%a1)
_halt:
    bra     _halt

_fail_l:
    lea     PASS_SENT, %a1
    move.l  #0xDEAD0FB1, %d2
    move.l  %d2, (%a1)
_h1:
    bra     _h1
_fail_w:
    lea     PASS_SENT, %a1
    move.l  #0xDEAD0FB2, %d2
    move.l  %d2, (%a1)
_h2:
    bra     _h2
_fail_b:
    lea     PASS_SENT, %a1
    move.l  #0xDEAD0FB3, %d2
    move.l  %d2, (%a1)
_h3:
    bra     _h3
_fail_s:
    lea     PASS_SENT, %a1
    move.l  #0xDEAD0FB4, %d2
    move.l  %d2, (%a1)
_h4:
    bra     _h4
_fail_d:
    lea     PASS_SENT, %a1
    move.l  #0xDEAD0FB5, %d2
    move.l  %d2, (%a1)
_h5:
    bra     _h5
_fline:
    lea     PASS_SENT, %a1
    move.l  #0xDEAD0F01, %d2
    move.l  %d2, (%a1)
_h6:
    bra     _h6
"""

  private val regDirectMergeProgram =
    """
    .text
    .org 0

    .equ PASS_SENT, 0xFFFF0000

_start:
    lea     0x00010000, %a7
    move.l  #_fline, 0x0000002C

    fmove.l #1234, %fp0              | int32 image 0x000004D2

    | .L is a full-width write: the whole seed is replaced.
    move.l  #0xAAAA5555, %d3
    fmove.l %fp0, %d3
    cmp.l   #0x000004D2, %d3
    bne     _fail_regl

    | .W merges into the LOW WORD only -- Dn[31:16] must survive untouched.
    move.l  #0xAAAA5555, %d4
    fmove.w %fp0, %d4
    cmp.l   #0xAAAA04D2, %d4
    bne     _fail_regw

    | .B merges into the LOW BYTE only -- Dn[31:8] must survive untouched.
    move.l  #0xAAAA5555, %d5
    fmove.b %fp0, %d5
    cmp.l   #0xAAAA55D2, %d5
    bne     _fail_regb

    lea     PASS_SENT, %a1
    move.l  #0xC0FFEE00, %d2
    move.l  %d2, (%a1)
_halt:
    bra     _halt

_fail_regl:
    lea     PASS_SENT, %a1
    move.l  #0xDEAD0FC1, %d2
    move.l  %d2, (%a1)
_h1:
    bra     _h1
_fail_regw:
    lea     PASS_SENT, %a1
    move.l  #0xDEAD0FC2, %d2
    move.l  %d2, (%a1)
_h2:
    bra     _h2
_fail_regb:
    lea     PASS_SENT, %a1
    move.l  #0xDEAD0FC3, %d2
    move.l  %d2, (%a1)
_h3:
    bra     _h3
_fline:
    lea     PASS_SENT, %a1
    move.l  #0xDEAD0F01, %d2
    move.l  %d2, (%a1)
_h4:
    bra     _h4
"""

  test("FMOVE FPn,(xxx).W stores the CORRECT BYTES for .L/.W/.B/.S/.D (no oracle possible)",
       VerilatorTest) {
    runProgram("fp-store-absw-values", absWProgram)
  }

  test("FMOVE.W/.B FPn,Dn merges into the low word/byte and preserves the rest (D11)",
       VerilatorTest) {
    runProgram("fp-store-regdirect-merge", regDirectMergeProgram)
  }
}
